"""Flashcards / Decks — AI-generated by topic name (or pasted text)."""
from flask import Blueprint, render_template, redirect, url_for, flash, abort, request
from flask_login import login_required, current_user
from .. import db
from ..models import Deck, Flashcard, StudyActivity
from ..forms import DeckTopicForm, DeckTextForm
from ..services.ai_service import generate_flashcards

flashcards_bp = Blueprint("flashcards", __name__)


@flashcards_bp.route("/")
@login_required
def index():
    decks = (Deck.query.filter_by(user_id=current_user.id)
             .order_by(Deck.created_at.desc()).all())
    return render_template("flashcards/list.html", decks=decks)


@flashcards_bp.route("/new", methods=["GET", "POST"])
@login_required
def new():
    """Default: generate by topic + number (the new flow)."""
    form = DeckTopicForm()
    if request.method == "GET":
        pre = request.args.get("topic")
        if pre:
            form.topic.data = pre
    if form.validate_on_submit():
        topic = form.topic.data.strip()
        count = int(form.count.data)
        deck = Deck(user_id=current_user.id, title=topic)
        db.session.add(deck)
        db.session.flush()

        cards = generate_flashcards(topic, n=count)
        for c in cards:
            db.session.add(Flashcard(deck_id=deck.id,
                                     question=c.get("question", "?"),
                                     answer=c.get("answer", "")))
        db.session.commit()
        flash(f"Generated {len(cards)} flashcards about '{topic}'.", "success")
        return redirect(url_for("flashcards.study", deck_id=deck.id))
    return render_template("flashcards/new.html", form=form)


@flashcards_bp.route("/new/text", methods=["GET", "POST"])
@login_required
def new_from_text():
    """Power-user: generate cards from pasted source text."""
    form = DeckTextForm()
    if form.validate_on_submit():
        deck = Deck(user_id=current_user.id, title=form.title.data)
        db.session.add(deck)
        db.session.flush()
        cards = generate_flashcards(form.source_text.data, n=int(form.count.data))
        for c in cards:
            db.session.add(Flashcard(deck_id=deck.id,
                                     question=c.get("question", "?"),
                                     answer=c.get("answer", "")))
        db.session.commit()
        flash(f"Generated {len(cards)} flashcards from text.", "success")
        return redirect(url_for("flashcards.study", deck_id=deck.id))
    return render_template("flashcards/new_text.html", form=form)


@flashcards_bp.route("/<int:deck_id>/study")
@login_required
def study(deck_id):
    deck = Deck.query.get_or_404(deck_id)
    if deck.user_id != current_user.id:
        abort(403)
    db.session.add(StudyActivity(user_id=current_user.id, kind="card"))
    db.session.commit()
    return render_template("flashcards/study.html", deck=deck)


@flashcards_bp.route("/<int:deck_id>")
@login_required
def view(deck_id):
    """List all Q/A in a deck (useful to skim/review)."""
    deck = Deck.query.get_or_404(deck_id)
    if deck.user_id != current_user.id:
        abort(403)
    return render_template("flashcards/view.html", deck=deck)


@flashcards_bp.route("/<int:deck_id>/regenerate", methods=["POST"])
@login_required
def regenerate(deck_id):
    """Generate a fresh set of cards for the same topic."""
    deck = Deck.query.get_or_404(deck_id)
    if deck.user_id != current_user.id:
        abort(403)
    Flashcard.query.filter_by(deck_id=deck.id).delete()
    n = int(request.form.get("count", 8))
    n = max(3, min(20, n))
    cards = generate_flashcards(deck.title, n=n)
    for c in cards:
        db.session.add(Flashcard(deck_id=deck.id,
                                 question=c.get("question", "?"),
                                 answer=c.get("answer", "")))
    db.session.commit()
    flash(f"Regenerated {len(cards)} cards.", "success")
    return redirect(url_for("flashcards.study", deck_id=deck.id))


@flashcards_bp.route("/<int:deck_id>/delete", methods=["POST"])
@login_required
def delete(deck_id):
    deck = Deck.query.get_or_404(deck_id)
    if deck.user_id != current_user.id:
        abort(403)
    db.session.delete(deck)
    db.session.commit()
    flash("Deck deleted.", "info")
    return redirect(url_for("flashcards.index"))